### ISSUE TITLE
generation issues

### ISSUE THREAD

**Issue by yodiyo** [CinKon/generator-uikit-webapp#3]
After installing and running gulp, I get this...

NB I've replaced my user filepath with %%%%%

`Using gulpfile ~/Sites/uikit-webapp/Gulpfile.js
[16:04:44] Starting 'coffee'...
[16:04:44] Starting 'styles'...
[16:04:44] 'styles' errored after 4.54 ms
[16:04:44] Error: Invalid glob argument: 
  at Gulp.src (/Users/%%%%/Sites/uikit-webapp/node_modules/vinyl-fs/lib/src/index.js:20:11)
  at Gulp.<anonymous> (/Users/%%%%%/Sites/uikit-webapp/gulpfile.coffee:119:8)
  at module.exports (/Users/%%%%%/Sites/uikit-webapp/node_modules/orchestrator/lib/runTask.js:34:7)
  at Gulp.Orchestrator._runTask (/Users/%%%%/Sites/uikit-webapp/node_modules/orchestrator/index.js:273:3)
  at Gulp.Orchestrator._runStep (/Users/%%%%/Sites/uikit-webapp/node_modules/orchestrator/index.js:214:10)
  at Gulp.Orchestrator.start (/Users/%%%%/Sites/uikit-webapp/node_modules/orchestrator/index.js:134:8)
  at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
  at nextTickCallbackWith0Args (node.js:452:9)
  at process._tickCallback (node.js:381:13)
  at Function.Module.runMain (module.js:449:11)
  at startup (node.js:139:18)
  at node.js:999:3
`

**Comment by CinKon** [comment]
Could you post your gulpfile.coffee?
Am 09.03.2016 17:32 schrieb "Yorick Brown" <notifications@github.com>:

**Comment by yodiyo** [comment]
`
coffee              = require 'gulp-coffee'
critical            = require 'critical'
criticalstream      = require('critical').stream
gulp                = require 'gulp'
imagemin            = require 'gulp-imagemin'
jade                = require 'gulp-jade'
less                = require 'gulp-less'
nano                = require 'cssnano'
notify              = require 'gulp-notify'
plumber             = require 'gulp-plumber'
postcss             = require 'gulp-postcss'
postcssrgba         = require 'postcss-color-rgba-fallback'
postcssshort        = require 'postcss-short'
pxtorem             = require 'postcss-pxtorem'
rucksack            = require 'gulp-rucksack'
rename              = require 'gulp-rename'
sourcemaps          = require 'gulp-sourcemaps'
uglify              = require 'gulp-uglify'
livereload          = require 'gulp-livereload'
connect             = require 'gulp-connect'
open                = require 'gulp-open'
port                = process.env.port || 8080
watch               = require 'gulp-watch'

paths =
  folders :
    css:        'css'
    less:       'src/less'
    coffee:     'src/coffeescript'
    scripts:    'js'
    images:     'img'
    templates:  'src/tpl'

  files :
    css:        'css/**/*.css'
    less:       'src/less/**/*.less'
    coffee:     'src/coffeescript/**/*.coffee'
    scripts:    'js/*.js'
    images:     'img/**/*'
    templates:  'src/tpl/*.jade'


# Compile only specified file
#var compileOnly = paths.folders.sass + "/landingpage.scss";
compileOnly = false;

# onError Start
onError = ( err ) ->

  # Initial building up of the error
  errorString = 'error: ' + '[' + err.plugin + ']'
  errorString += ' ' + err.message.replace("\n",''); # Removes new line at the end

  # If the error contains the filename or line number add it to the string
  if err.fileName
      errorString += ' in ' + err.fileName

  if err.lineNumber
      errorString += ' on line ' + err.lineNumber

  # This will output an error like the following:
  # [gulp-sass] error message in file_name on line 1
  console.error(errorString);

  this.emit( 'end' )
# END



# Styles
gulp.task 'styles', ->

  if compileOnly != false
    srcFile = compileOnly
  else
    srcFile = paths.files.stylus

  processors = [
    postcssshort()
    nano(safe: true)
    pxtorem(
      replace: false
      prop_white_list: [
        'padding'
        'margin'
        'width'
        'height'
        'min-width'
        'min-height'
        'max-width'
        'max-height'
        'font'
        'font-size'
        'line-height'
        'letter-spacing'
        'top'
        'left'
        'bottom'
        'right'
      ]
      selector_black_list: [
        'body'
        'html'
      ])
    postcssrgba(properties: [
      'background-color'
      'background'
      'color'
      'border'
      'border-color'
      'outline'
      'outline-color'
      'box-shadow'
      'text-shadow'
    ])
  ]

  gulp.src([ srcFile ], base: paths.folders.less)
    .pipe( plumber({ errorHandler: notify.onError("Error: <%= error.message %>") }))
    .pipe(sourcemaps.init())
    .pipe(less())
    .pipe(rucksack(
      autoprefixer: true
    ))
    .pipe(postcss(processors))
    .pipe(sourcemaps.write('.'))
    .pipe(gulp.dest(paths.folders.css))
    .pipe(livereload())
    .pipe notify(
      message: 'Styles task complete'
      title: 'Styles'
      onLast: true)
# END

###
# Find Critical Above The Fold CSS
# And output inline
###
gulp.task 'criticalin', [ 'styles' ], ->
  gulp.src('*.html', base: '.').pipe(criticalstream(
    inline: true
    base: '.'
    minify: true
    dimensions: [
      {
        height: 500
        width: 768
      }
      {
        height: 800
        width: 960
      }
      {
        height: 1000
        width: 1200
      }
    ])).pipe gulp.dest('.')
# END


# Don't forget to link to critical.css File
# <link rel="stylesheet" href="css/critical.css">
gulp.task 'criticalext', ->
  gulp.src('*.html', base: '.').pipe(criticalstream(
    inline: false
    base: '.'
    css: 'css/style.css'
    dest: paths.folders.css + '/critical.css'
    minify: true
    dimensions: [
      {
        height: 500
        width: 768
      }
      {
        height: 800
        width: 960
      }
      {
        height: 1000
        width: 1200
      }
    ])).pipe gulp.dest('.')

# Scripts
gulp.task 'scripts', ->
  gulp.src(paths.files.scripts)
    .pipe(plumber({ errorHandler: notify.onError("Error: <%= error.message %>") }))
    .pipe(sourcemaps.init())
    .pipe(rename(suffix: '.min'))
    .pipe(uglify())
    .pipe(sourcemaps.write('.', sourceRoot: paths.folders.coffee))
    .pipe(gulp.dest(paths.folders.scripts + '/min'))
    .pipe(livereload())
    .pipe notify(
      message: 'Scripts task complete'
      title: 'JS'
      onLast: true)
# END


# Coffee Script
gulp.task 'coffee', ->
  gulp.src([ paths.files.coffee ], base: paths.folders.coffee)
    .pipe(plumber({ errorHandler: notify.onError("Error: <%= error.message %>") }))
    .pipe(sourcemaps.init())
    .pipe(coffee(bare: true))
    .pipe(sourcemaps.write('.'))
    .pipe(gulp.dest(paths.folders.scripts))
    .pipe notify(
      message: 'Coffee task complete'
      title: 'Coffee'
      onLast: true)
# END



# Images
gulp.task 'images', ->
  gulp.src(paths.files.images, base: '.')
    .pipe(plumber({ errorHandler: notify.onError("Error: <%= error.message %>") }))
    .pipe(imagemin(
      optimizationLevel: 3
      progressive: true
      interlaced: true))
    .pipe(gulp.dest('.'))
    .pipe notify(
      message: 'Image task complete'
      title: 'Image'
      onLast: true)
# END



# Jade Templates
gulp.task 'jade', ->
  gulp.src(paths.files.templates)
    .pipe(plumber({ errorHandler: notify.onError("Error: <%= error.message %>") }))
    .pipe(jade(pretty: '  '))
    .pipe(gulp.dest('.'))
    .pipe(livereload())
    .pipe notify(
      message: 'Template task complete'
      title: 'Jade'
      onLast: true)
# END





# Webserver
gulp.task 'webserver', ->
  connect.server
    port: port
    host: 'local.dev'
  return
# END

#launch browser in port
gulp.task 'open', ->
  options = url: 'http://localhost:' + port
  gulp.src('./index.html').pipe open('', options)
  return
# END


#gulp.task('default', ['coffee', 'styles', 'scripts', 'images', 'jade', 'webserver', 'open'], function() {
gulp.task 'default', [
  'coffee'
  'styles'
  'scripts'
  'images'
  'jade'
  'webserver'
  'open'
], ->
  
  livereload.listen();
  
  
  
  gulp.watch paths.files.less, [ 'styles' ]
  
  
  # Watch Styles task for sass Files
  gulp.watch paths.files.coffee, [ 'coffee' ]
  # Watch Coffee Task for templates Files
  gulp.watch paths.files.templates, [ 'jade' ]
  # Watch Jade Task for templates Files
  gulp.watch paths.files.scripts, [ 'scripts' ]
  # Minify/JSHint only js-files in /js-root
  return
`

**Comment by CinKon** [comment]
Ah, i can see, whats the problem. I'm sorry, I don't use less myself with this generator, so I don't look after it very regular... ;)
To solve the problem quickly: At line 101 replace `srcFile = paths.files.stylus` with `srcFile = paths.files.less`

I'll fix it in the repository, thanks for the hint

**Comment by yodiyo** [comment]
Great, that works. Thanks so much.
