### ISSUE TITLE
missing modernizr.js in js/vendor/

### ISSUE THREAD

**Issue by aptly-io** [CinKon/generator-uikit-webapp#6]
In my browser console I see a 404 when it tries to load http://localhost:5000/js/vendor/moderniz.js

These are the steps I did to install uikir-webapp:
```bash
INST_DIR=yo-uikit-trial
rm -rf $INST_DIR
mkdir $INST_DIR
cd $INST_DIR
export PATH=./node_modules/.bin:$PATH
npm install yo bower generator-uikit-webapp
yo uikit-webapp
```

These are my answer's to yo's questions (default answers except for the test)
```
? What is your app's name ? test
? Would you like to use a Task-Runner for compiling? Gulp
? Which precompiler-language do you want to use? SASS
? Do you need Babel for EcmaScript2015? No
? Do you need Coffeescript compiling? Yes
? Do you want to use a Browser-connection? BrowserConnect (includes Livereload, connects multiple Browsers/Devices)
? Would you like to use a Framework? UIKit
```

There were some error outputs in the process (that I don't know how to fix these ...)
- I read on the internet this one is not to take serious:
```
✖ npm version
Your npm version is outdated.
```
- I guess this means modernizr is not found? Is it a pre requisite?
  I solved it with  `npm install modernizr`
```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn modernizr ENOENT
    at exports._errnoException (util.js:873:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```

Maybe mention that modernizr is a prerequisite for successful running this generator in the readme.md?

**Comment by CinKon** [comment]
You're right. I always had modernizr installed globally.
I added it as a devDependency.

**Comment by aptly-io** [comment]
Thanks for the fast response!
