### ISSUE TITLE
Several links are not found, odd looking page

### ISSUE THREAD

**Issue by aptly-io** [CinKon/generator-uikit-webapp#7]
In my browser I see a webpage with the title `test` at the end of running the install script below.
When I click on a link in the nav bar at the top named: Brand, Frontpage, Portfolio, Blog, Documentation, Contact, Login I get these 404 errors:
Cannot GET /layouts_frontpage.html, Cannot GET /layouts_frontpage.html, etc

These are the steps I did to install uikir-webapp:
```bash
INST_DIR=yo-uikit-trial
rm -rf $INST_DIR
mkdir $INST_DIR
cd $INST_DIR
export PATH=./node_modules/.bin:$PATH
npm install yo bower generator-uikit-webapp modernizr
yo uikit-webapp
```

These are my answer's to yo's questions (default answers except for the test)

? What is your app's name ? test
? Would you like to use a Task-Runner for compiling? Gulp
? Which precompiler-language do you want to use? SASS
? Do you need Babel for EcmaScript2015? No
? Do you need Coffeescript compiling? Yes
? Do you want to use a Browser-connection? BrowserConnect (includes Livereload, connects multiple Browsers/Devices)
? Would you like to use a Framework? UIKit

There was some error output in the process (that I don't know how to fix ...)
- I read on the internet this one is not to take serious:
```
✖ npm version
Your npm version is outdated.
```

1. What should I do to fix these links? Maybe these were meant to be fragment URLs that jump into the SPA itself?
1. I tried this generator hoping to get a nice looking web page, illustrating uikit capabilities. But overall the page layout looks rather odd. Maybe due to all the sub pages that not really explain the uikit classes being used ...

Maybe it's because I have a misunderstanding of what yo and the generator are exactly used for ...

**Comment by CinKon** [comment]
This generator delivers only a front-page with demo-ui-elements, not a complete functional website.
In general, that's what yeoman is for. It delivers individual starting-points for your project.

**Comment by aptly-io** [comment]
Okay, understood. Thanks for the fast response!
